### ISSUE TITLE
默認排序是倒序的？能變爲順序嗎？

### ISSUE THREAD

**Issue by wby238** [kanasimi/comic#2]
下載漫畫時發現保存的目錄名按倒序排列了，請問能變爲順序排列嗎？
使用的是manhuatai.js

**Comment by wby238** [comment]
用了其他的.js後目前發現只有manhuatai.js的按倒序排列是失效的，刪去if改爲強制執行才能倒序排列。

**Comment by kanasimi** [comment]
感謝您的試用並回報問題。不知能麻煩您描述一下**刪去if改爲強制執行**的方法嗎?

**Comment by kanasimi** [comment]
已修正，請重新下載測試，謝謝。若仍有問題，您可 reopen issue。

**Comment by wby238** [comment]
感謝您的修復，已經變成順序排列了。
雖然manhuatai還有一些漫畫下不了，但用ikanman的代替就行了。

**Comment by kanasimi** [comment]
> manhuatai還有一些漫畫下不了
這是指本工具的問題嗎? 若如此，請開個 issue 描述一下，謝謝。
