### ISSUE TITLE
manhuatai.js無法下載某些作品

### ISSUE THREAD

**Issue by wby238** [kanasimi/comic#5]
在下載某些作品時總是會全部失敗，具體情況爲爲：

> 要下載的所有圖片都無法下載，保存的圖片全部爲0字節，且全部有bad後綴，錯誤信息照常記錄。

稍微看了看那些作品，目前發現都是知音漫客的作品（存疑），然後打開對應網頁自己試了一下，發現一些問題（以《浪漫传说》第一回 第一页 爲例）：
1. 這是manhuatai.js得出的下載鏈接：

> http://mhpic.xiaoshuomanhua.com/comic/L%2F%E6%B5%AA%E6%BC%AB%E4%BC%A0%E8%AF%B4%2F01%E8%AF%9D%2F1.jpg

自己用瀏覽器打開鏈接，返回：
```json
{
  "error": "Document not found"
}
```

2. 這是打開對應頁面時找到的下載鏈接：

> http://mhpic.zymk.cn/comic/L%2F%E6%B5%AA%E6%BC%AB%E4%BC%A0%E8%AF%B4%2F01%E8%AF%9D%2F1.jpg-mht.middle

此時得到正確的圖片。

3. 用2中的mhpic.zymk.cn來替換1得到的鏈接：

> http://mhpic.zymk.cn/comic/L%2F%E6%B5%AA%E6%BC%AB%E4%BC%A0%E8%AF%B4%2F01%E8%AF%9D%2F1.jpg

此時返回：
```json
{
  "error": "download token not specified"
}
```
猜測這是因爲網站將某些作品的圖片放在特定的服務器上。
附目前有問題的作品：
《浪漫传说》、《星海镖师》、《天行轶事》、《白夜玲珑》、《偷星九月天》、《风起苍岚》、《善良的死神/善良的阿呆》

除此之外，還有一些非知音漫客的作品也有個別圖片是這種現象，例如：《豌豆笑传》。
【
然後還有一些作品的個別圖片是完整的，卻依然加了bad後綴（可能是因爲沒有EOI？），例如：《老夫子》。
再然後還有一些作品的個別圖片本來就是不完整的，這也會加bad後綴，；自如：《知音漫客》。
】
【】中的問題我覺得不是很大，可以不用去管。
最後就是其實ikanman和manhuatai之間是替代品，只要其中一個能用就行了……

**Comment by kanasimi** [comment]
manhuatai 改版了...可能得費點時間

**Comment by kanasimi** [comment]
npm 安裝的不是最新版，有些新功能尚未加入，請見諒。
您需要直接到 GitHub 下載最新版本 [CeJS](https://github.com/kanasimi/CeJS) 壓縮檔，解開後配置。
